#!hint/zsh
local purple="$(tput setaf 35)" bright="$(tput bold)" green="$(tput setaf 32)" reset="$(tput sgr0)"
printf 'zsh: command not found: %s\n' "$1"
local entries=(
	${(f)"$(/usr/bin/pacman -F --machinereadable -- "/usr/bin/$1")"}
)
if ((${#entries[@]}))
then
	printf "${bright}$1${reset} may be found in the following packages:\n"
	local pkg
	for entry in "${entries[@]}"
	do
		# (repo package version file)
		local fields=(
			${(0)entry}
		)
		if [[ "$pkg" != "${fields[2]}" ]]
		then
			printf "${purple}%s/${bright}%s ${green}%s${reset}\n" "${fields[1]}" "${fields[2]}" "${fields[3]}"
		fi
		printf '	/%s\n' "${fields[4]}"
		pkg="${fields[2]}"
	done
fi
